name: Build
on:
  push:
    branches:
      - master
    paths-ignore:
      - "website"
      - "CHANGELOG.md"
  workflow_call:
    inputs:
      environment:
        type: string
        required: false
        default: ""
  workflow_dispatch:
jobs:
  build:
    name: "Build (Windows x64)"
    environment: ${{ inputs.environment }}
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: "yarn"
      - name: Cache
        uses: actions/cache@v5
        with:
          path: "node_modules"
          key: ${{ runner.os }}-build-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: |
          yarn install --immutable --network-timeout 120000
      - name: Build
        if: inputs.environment != 'Release'
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"
        run: |
          yarn build
          yarn lerna run build:win-x64 --stream
      - name: Build (Release)
        if: inputs.environment == 'Release'
        env:
          CSC_LINK: ${{ secrets.APPLE_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          yarn build
          yarn lerna run build:win-x64 --stream
      - name: Upload x64 builds
        uses: actions/upload-artifact@v6
        with:
          name: built-app-x64-win
          path: |
            app/electron/dist/Pomatez*x64*.*
            app/electron/dist/Pomatez*x86_64*.*
            app/electron/dist/Pomatez*amd64*.*
      - name: Upload autoupdaters
        uses: actions/upload-artifact@v6
        with:
          name: built-app-AutoUpdater-win
          path: |
            app/electron/dist/latest*
